spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: Binarfud
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/binarfud/**
#        - id: Consumer
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/consumer/**
server:
  port: 8080

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka